### ISSUE TITLE
Tag the releases

### ISSUE THREAD

**Issue by juho-jaakkola** [nlybe/Elgg-MapsAPI#1]
Both https://packagist.org/packages/nlybe/groupsmap and https://packagist.org/packages/nlybe/membersmap require the version `2.9.x` of the plugin.

Any releases haven't however been made of the plugin: https://github.com/nlybe/Elgg-MapsAPI/releases

Add the `2.9.4` release from command line with:
```
git tag -a 2.9.4
git push origin 2.9.4
```

**Comment by nlybe** [comment]
Done
