### ISSUE TITLE
Missing dependencies 

### ISSUE THREAD

**Issue by AndreyAtGitHub** [nlybe/Elgg-MapsAPI#3]
Hi! 
Trying to save the settings for the plugin Elgg-MapsApi in Elgg 2.3.11 - caused this error in the php_errors.log file and the Fatal Error at the web browser.

`[25-Dec-2018 16:30:59 UTC] Exception at time 1545755459: Error: Class 'Ivory\HttpAdapter\CurlHttpAdapter' not found in C:\server\data\htdocs\mod\amap_maps_api\lib\amap_maps_api.php:44
Stack trace:
#0 C:\server\data\htdocs\mod\amap_maps_api\actions\amap_maps_api\admin\settings.php(14): amap_ma_geocode_location('Europe')
#1 C:\server\data\htdocs\vendor\elgg\elgg\engine\classes\Elgg\Includer.php(18): include('C:\\server\\data\\...')
#2 C:\server\data\htdocs\vendor\elgg\elgg\engine\classes\Elgg\ActionsService.php(176): Elgg\Includer::includeFile('C:/server/data/...')
#3 C:\server\data\htdocs\vendor\elgg\elgg\engine\lib\actions.php(22): Elgg\ActionsService->execute('amap_maps_api/a...')
#4 [internal function]: _elgg_action_handler(Array, 'action')
#5 C:\server\data\htdocs\vendor\elgg\elgg\engine\classes\Elgg\Router.php(100): call_user_func('_elgg_action_ha...', Array, 'action')
#6 C:\server\data\htdocs\vendor\elgg\elgg\engine\classes\Elgg\Application.php(436): Elgg\Router->route(Object(Elgg\Http\Request))
#7 C:\server\data\htdocs\vendor\elgg\elgg\engine\classes\Elgg\Application.php(384): Elgg\Application->run()
#8 C:\server\data\htdocs\index.php(8): Elgg\Application::index()
#9 {main}
`

**Comment by AndreyAtGitHub** [comment]
Changing the version of "willdurand/geocoder": "3.3.2" from stable in the composer.json resolve the issue.

`{
    "name": "nlybe/amap_maps_api",
    "type": "elgg-plugin",
    "require": {
        "php": ">=5.3.3",
        "composer/installers": ">=1.0.8",
        "willdurand/geocoder": "3.3.2",
        "treffynnon/navigator": "1.0.0"
    },        
    "license": "GPL-2.0"
}
`

**Comment by umerzeeshan** [comment]
Hello,
Sorry for asking basic question, I activated the plugin with 2.3.7 version but there is no change in the site, am I missing something, I didn't face any error but no option to share a map etc, how should I use this plugin?

**Comment by nlybe** [comment]
@umerzeeshan 
> Hello,
> Sorry for asking basic question, I activated the plugin with 2.3.7 version but there is no change in the site, am I missing something, I didn't face any error but no option to share a map etc, how should I use this plugin?

You can't use this plugin as standalone. It's used as basis for other plugins such as 
- https://github.com/nlybe/Elgg-Membersmap
- https://github.com/nlybe/Elgg-Groupsmap
- https://github.com/nlybe/Elgg-Photosmap
- https://github.com/nlybe/Elgg-Pagesmap
